package com.programmersbox.tutorial.calculator.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCalculator = createDescriptorForCalculator();
  /*package*/ final ConceptDescriptor myConceptInputField = createDescriptorForInputField();
  /*package*/ final ConceptDescriptor myConceptInputFieldReference = createDescriptorForInputFieldReference();
  /*package*/ final ConceptDescriptor myConceptOutputField = createDescriptorForOutputField();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
    deps.aggregatedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCalculator, myConceptInputField, myConceptInputFieldReference, myConceptOutputField);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Calculator:
        return myConceptCalculator;
      case LanguageConceptSwitch.InputField:
        return myConceptInputField;
      case LanguageConceptSwitch.InputFieldReference:
        return myConceptInputFieldReference;
      case LanguageConceptSwitch.OutputField:
        return myConceptOutputField;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCalculator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.programmersbox.tutorial.calculator", "Calculator", 0x7aba7972e859401eL, 0xabb804e209b23681L, 0x34c062b950e23fc9L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:87868840-0078-4f9f-9a21-02b78c7c913c(com.programmersbox.tutorial.calculator.structure)/3801146633566175177");
    b.version(3);
    b.aggregate("inputField", 0x34c062b950e27511L).target(0x7aba7972e859401eL, 0xabb804e209b23681L, 0x34c062b950e274f4L).optional(true).ordered(true).multiple(true).origin("3801146633566188817").done();
    b.aggregate("outputField", 0x34c062b950e29288L).target(0x7aba7972e859401eL, 0xabb804e209b23681L, 0x34c062b950e29278L).optional(true).ordered(true).multiple(true).origin("3801146633566196360").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.programmersbox.tutorial.calculator", "InputField", 0x7aba7972e859401eL, 0xabb804e209b23681L, 0x34c062b950e274f4L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:87868840-0078-4f9f-9a21-02b78c7c913c(com.programmersbox.tutorial.calculator.structure)/3801146633566188788");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputFieldReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.programmersbox.tutorial.calculator", "InputFieldReference", 0x7aba7972e859401eL, 0xabb804e209b23681L, 0x34c062b950e2f1dfL);
    b.class_(false, false, false);
    // extends: jetbrains.mps.baseLanguage.structure.Expression
    b.super_(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:87868840-0078-4f9f-9a21-02b78c7c913c(com.programmersbox.tutorial.calculator.structure)/3801146633566220767");
    b.version(3);
    b.associate("field", 0x34c062b950e2f1e5L).target(0x7aba7972e859401eL, 0xabb804e209b23681L, 0x34c062b950e274f4L).optional(false).origin("3801146633566220773").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOutputField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("com.programmersbox.tutorial.calculator", "OutputField", 0x7aba7972e859401eL, 0xabb804e209b23681L, 0x34c062b950e29278L);
    b.class_(false, false, false);
    b.origin("r:87868840-0078-4f9f-9a21-02b78c7c913c(com.programmersbox.tutorial.calculator.structure)/3801146633566196344");
    b.version(3);
    b.aggregate("expression", 0x34c062b950e2b461L).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("3801146633566205025").done();
    return b.create();
  }
}
